<?php

namespace SiteBundle\Repository;

use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use SiteBundle\Entity\AdsAdditionalInfo;

/**
 * AdsAdditionalInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
final class AdsAdditionalInfoRepository extends ExtendedEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, AdsAdditionalInfo::class);
    }

    public function getByAdsId($id)
    {
        $query = $this->createQueryBuilder('aai')
            ->select(
                'aai.id AS InfoId',
                'aai.capacitymin AS CapacityMin',
                'aai.capacitymax AS CapacityMax',
                'aai.description AS Description'
            )
            ->where('aai.adsid = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();

        return $query;
    }
}
