<?php

declare(strict_types=1);

namespace SiteBundle\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use SiteBundle\Entity\AdsPayedDate;

/**
 * Adspayeddaterepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
final class Adspayeddaterepository extends ExtendedEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, AdsPayedDate::class);
    }
}
