<?php

declare(strict_types=1);

namespace SiteBundle\Repository;

use Doctrine\Persistence\ManagerRegistry;
use SiteBundle\Entity\Role;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
final class RoleRepository extends ExtendedEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Role::class);
    }
}
