<?php

declare(strict_types=1);

namespace SiteBundle\Repository;

use Doctrine\Persistence\ManagerRegistry;
use SiteBundle\Entity\UserToSocialNetwork;

/**
 * UserToSocialNetworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
final class UserToSocialNetworkRepository extends ExtendedEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, UserToSocialNetwork::class);
    }
}
