admin:
    resource: "@AdminBundle/Controller/"
    prefix: /
    type: attribute
    options:
        expose: true

admin.login:
    path: /login
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: '@Admin/Pages/login.html.twig'

admin.logout:
    path: /logout

admin.dashboard:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: '@Admin/Pages/dashboard.html.twig'

admin.users:
    path: /users
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: '@Admin/Pages/users.html.twig'
