imports:
    - { resource: config.yml }
    - { resource: ads.yml }
    - { resource: monolog_prod.yaml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
