_errors:
    resource: "@FrameworkBundle/Resources/config/routing/errors.php"
    prefix:   /_error


PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.php"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

admin:
    resource: "@AdminBundle/Resources/config/admin_routing.yml"
    prefix: /admin
    options:
        expose: true

admin_api:
    resource: "@AdminBundle/Resources/config/admin_api_routing.yml"
    prefix: /admin/api
    options:
        expose: true

site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /
    options:
        expose: true

#api_annotation:
#    resource: "@SiteBundle/Controller/"
#    type: annotation
#    prefix: /api/
#    options:
#        expose: true
