api:
  resource: "@SiteBundle/Resources/config/apiRouting.yml"
  prefix: /api/
  options:
    expose: true

core:
  resource: '@SiteBundle/Controller'
  type: attribute

site_index:
  defaults: { _controller: SiteBundle\Controller\IndexController::indexAction }
  path: /
  options:
    sitemap:
      priority: 0.7
      changefreq: weekly
      section: default

site_single_ads:
  path: /pregled/{category}/{alias}
  defaults: { _controller: SiteBundle\Controller\Ads\AdsGetController::singleAdsAction }

site_login_check:
  path: /site-login-check

site_logout:
  path: /site-logout

#site_activate_registration:
#  path: /aktivacija-naloga/{id}
#  defaults: { _controller: SiteBundle\Controller\User\UserEditController::activateRegistrationAction }
#  requirements:
#    id: \d+

site_about_us:
  path: /o-nama
  defaults:
      _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
      template: '@Site/Site/aboutUs.html.twig'

site_contact_us:
  path: /kontakt
  defaults:
      _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
      template: '@Site/Site/contactus.html.twig'
  options:
    sitemap:
      priority: 0.1
      changefreq: never
      section: default

site_reservation_success:
  path: /uspesna-rezervacija/{reservationId}/{alias}
  defaults: { _controller: SiteBundle\Controller\Reservation\ReservationGetController::successReservationPageAction }
  requirements:
    reservationId: \d+

#site_logo_email:
#  path: /logo.png
#  defaults: { _controller: SiteBundle\Controller\SiteImageController::getLogoEmailAction }

#site_logo:
#  path: /apartmani-sobe-crna-gora/logo.png
#  defaults: { _controller: SiteBundle\Controller\SiteImageController::getLogoAction }

site_ads_view:
  path: /{category}/{extraParams}
  controller: SiteBundle\Controller\Ads\AdsIndexController::indexAction
  defaults:
    extraParams: null
  requirements:
    category: "^(?!build)[a-zA-Z-]+"
    extraParams: .*
  methods: [GET]
